version: "3.9"

services:
  sql-cli:
    build: .
    container_name: sql-cli
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_USER: sqlviz
      MYSQL_PASSWORD: sqlviz123
    stdin_open: true
    tty: true

